'use client'

import React from 'react'
import { TrendingUp, MapPin, Calendar, Award } from 'lucide-react'

export default function V3StudentResults() {
  const studentResults = [
    {
      name: "Priya Sharma",
      location: "Pune, Maharashtra",
      image: "PS",
      beforeStory: "Complete beginner with no trading knowledge",
      afterStory: "Now earning ₹50,000+ monthly from trading",
      timeframe: "6 months",
      course: "Complete Trading Bundle",
      keyLearning: "Price action trading and risk management",
      results: [
        "₹50,000+ monthly trading income",
        "85% success rate on trades",
        "Built ₹5L trading portfolio"
      ]
    },
    {
      name: "Rahul Patil",
      location: "Mumbai, Maharashtra", 
      image: "RP",
      beforeStory: "Lost ₹2 lakh due to emotional trading",
      afterStory: "Recovered losses and now consistently profitable",
      timeframe: "8 months",
      course: "Technical Analysis + Psychology",
      keyLearning: "Emotional control and systematic approach",
      results: [
        "Recovered ₹2L losses completely",
        "80% win rate with new system",
        "₹3L+ profits in last 6 months"
      ]
    },
    {
      name: "Sunita Deshmukh",
      location: "Nashik, Maharashtra",
      image: "SD", 
      beforeStory: "Homemaker with only FD investments",
      afterStory: "Contributing ₹25,000+ monthly to family income",
      timeframe: "4 months",
      course: "Stock Market Fundamentals",
      keyLearning: "Safe investment strategies and market basics",
      results: [
        "₹25,000+ monthly passive income",
        "15-20% annual returns vs 6% FD",
        "Built diversified portfolio"
      ]
    },
    {
      name: "Amit Joshi",
      location: "Nagpur, Maharashtra",
      image: "AJ",
      beforeStory: "Business owner wanting additional income",
      afterStory: "Created multiple income streams through trading",
      timeframe: "10 months", 
      course: "Options Trading + Systems",
      keyLearning: "Options strategies and system creation",
      results: [
        "₹1.2L+ monthly options income",
        "Created 3 different trading systems",
        "Teaching trading to other businessmen"
      ]
    },
    {
      name: "Meera Kulkarni",
      location: "Aurangabad, Maharashtra",
      image: "MK",
      beforeStory: "Bank employee with traditional mindset",
      afterStory: "Became confident trader alongside banking job",
      timeframe: "7 months",
      course: "Complete Trading Bundle", 
      keyLearning: "Balancing job and trading activities",
      results: [
        "₹40,000+ trading income monthly",
        "Maintained banking job successfully", 
        "Helping colleagues with investments"
      ]
    },
    {
      name: "Vikram Singh",
      location: "Solapur, Maharashtra",
      image: "VS",
      beforeStory: "Retired person looking for income sources",
      afterStory: "Found perfect retirement income solution",
      timeframe: "5 months",
      course: "Conservative Trading Strategies",
      keyLearning: "Low-risk, steady income methods",
      results: [
        "₹30,000+ monthly retirement income",
        "Very low risk conservative approach",
        "Secured family's financial future"
      ]
    }
  ]

  const overallStats = [
    { label: "Total Students", value: "25,000+", description: "Trained since 2017" },
    { label: "Success Rate", value: "87%", description: "Become profitable traders" },
    { label: "Total Profits", value: "₹2.5Cr+", description: "Generated by students" },
    { label: "Average Returns", value: "18%", description: "Annual student returns" }
  ]

  return (
    <section className="py-16 bg-white">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <div className="text-center mb-16">
          <h2 className="text-4xl md:text-5xl font-light text-gray-800 mb-6">
            Real Students,{' '}
            <span className="bg-gradient-to-r from-green-600 to-blue-600 bg-clip-text text-transparent font-medium">
              Real Results
            </span>
          </h2>
          <p className="text-xl text-gray-600 max-w-3xl mx-auto mb-8">
            See how our institute students from across Maharashtra have transformed their financial lives 
            through practical trading education and ongoing mentorship.
          </p>

          {/* Overall Statistics */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-6 max-w-4xl mx-auto">
            {overallStats.map((stat, index) => (
              <div key={index} className="bg-gradient-to-br from-green-50 to-blue-50 rounded-xl p-6 border border-green-100">
                <div className="text-3xl font-light text-green-600 mb-2">{stat.value}</div>
                <div className="font-semibold text-gray-800 text-sm mb-1">{stat.label}</div>
                <div className="text-gray-500 text-xs">{stat.description}</div>
              </div>
            ))}
          </div>
        </div>

        {/* Student Success Stories */}
        <div className="grid lg:grid-cols-2 gap-8 mb-16">
          {studentResults.map((student, index) => (
            <div
              key={index}
              className="bg-white rounded-2xl p-8 shadow-lg border border-gray-100 hover:shadow-xl transition-shadow"
            >
              {/* Student Header */}
              <div className="flex items-start space-x-4 mb-6">
                <div className="w-16 h-16 bg-gradient-to-r from-blue-500 to-purple-500 rounded-full flex items-center justify-center flex-shrink-0">
                  <span className="text-white font-bold text-lg">{student.image}</span>
                </div>
                <div className="flex-1">
                  <h3 className="text-xl font-semibold text-gray-800 mb-1">{student.name}</h3>
                  <div className="flex items-center space-x-2 text-gray-500 text-sm mb-2">
                    <MapPin className="w-4 h-4" />
                    <span>{student.location}</span>
                  </div>
                  <div className="flex items-center space-x-4 text-sm">
                    <div className="flex items-center space-x-1">
                      <Calendar className="w-4 h-4 text-green-500" />
                      <span className="text-green-600 font-semibold">{student.timeframe}</span>
                    </div>
                    <div className="bg-blue-100 text-blue-800 px-3 py-1 rounded-full font-semibold">
                      {student.course}
                    </div>
                  </div>
                </div>
              </div>

              {/* Before/After Story */}
              <div className="mb-6">
                <div className="grid md:grid-cols-2 gap-4">
                  <div className="bg-red-50 border border-red-200 rounded-lg p-4">
                    <div className="text-red-800 font-semibold text-sm mb-2">BEFORE</div>
                    <p className="text-red-700 text-sm">{student.beforeStory}</p>
                  </div>
                  <div className="bg-green-50 border border-green-200 rounded-lg p-4">
                    <div className="text-green-800 font-semibold text-sm mb-2">AFTER</div>
                    <p className="text-green-700 text-sm">{student.afterStory}</p>
                  </div>
                </div>
              </div>

              {/* Key Learning */}
              <div className="mb-6">
                <div className="bg-blue-50 border-l-4 border-blue-500 rounded-r-lg p-4">
                  <div className="text-blue-800 font-semibold text-sm mb-2">KEY LEARNING</div>
                  <p className="text-blue-700 text-sm">{student.keyLearning}</p>
                </div>
              </div>

              {/* Specific Results */}
              <div>
                <div className="text-gray-800 font-semibold text-sm mb-3">SPECIFIC ACHIEVEMENTS</div>
                <div className="space-y-2">
                  {student.results.map((result, resultIndex) => (
                    <div key={resultIndex} className="flex items-center space-x-3">
                      <div className="w-2 h-2 bg-green-500 rounded-full flex-shrink-0"></div>
                      <span className="text-gray-700 text-sm">{result}</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Video Testimonials Section */}
        <div className="bg-gradient-to-r from-blue-600 to-purple-600 rounded-3xl p-8 md:p-12 text-white text-center mb-16">
          <h3 className="text-3xl font-light mb-6">
            Watch Student{' '}
            <span className="text-yellow-300 font-medium">Success Videos</span>
          </h3>
          <p className="text-blue-100 mb-8 max-w-2xl mx-auto">
            Hear directly from our students about their journey from beginners to successful traders
          </p>
          
          <div className="grid md:grid-cols-3 gap-6 mb-8">
            {[
              { title: "From ₹0 to ₹50K Monthly", duration: "3:24", views: "12K" },
              { title: "Recovered ₹2L Losses", duration: "2:47", views: "8.5K" },
              { title: "Homemaker's Success Story", duration: "4:12", views: "15K" }
            ].map((video, index) => (
              <div
                key={index}
                className="bg-white/20 backdrop-blur-lg rounded-2xl p-6 border border-white/30 hover:bg-white/30 transition-colors cursor-pointer"
              >
                <div className="w-16 h-16 bg-white/30 rounded-full flex items-center justify-center mx-auto mb-4">
                  <div className="w-0 h-0 border-l-12 border-l-white border-y-8 border-y-transparent ml-1"></div>
                </div>
                <h4 className="font-semibold mb-2">{video.title}</h4>
                <div className="text-blue-200 text-sm space-x-2">
                  <span>{video.duration}</span>
                  <span>•</span>
                  <span>{video.views} views</span>
                </div>
              </div>
            ))}
          </div>

          <button className="bg-white text-blue-600 px-8 py-4 rounded-xl font-semibold hover:bg-gray-100 transition-colors">
            Watch All Success Stories
          </button>
        </div>

        {/* Call to Action */}
        <div className="text-center">
          <div className="bg-gradient-to-br from-green-50 to-blue-50 rounded-2xl p-8 border border-green-200">
            <h3 className="text-2xl md:text-3xl font-light text-gray-800 mb-6">
              Ready to Write Your Own{' '}
              <span className="text-green-600 font-medium">Success Story?</span>
            </h3>
            <p className="text-gray-600 mb-8 max-w-2xl mx-auto">
              Join thousands of successful students who started exactly where you are now. 
              Your transformation story could be next on this list.
            </p>
            
            <div className="grid sm:grid-cols-2 gap-6 max-w-lg mx-auto">
              <button className="bg-gradient-to-r from-green-600 to-blue-600 hover:from-green-700 hover:to-blue-700 text-white font-bold py-4 px-6 rounded-xl transition-colors">
                Start Your Journey - Join Institute
              </button>
              <button className="border-2 border-gray-300 text-gray-700 hover:border-green-600 hover:text-green-600 font-semibold py-4 px-6 rounded-xl transition-colors">
                Talk to Successful Students
              </button>
            </div>

            <div className="mt-6 text-sm text-gray-500 space-y-1">
              <div>✅ No payment required to start</div>
              <div>📞 Call +91-7066334499 to speak with our successful students</div>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}